//criteria
export const SET_KEYWORDS = 'SET_KEYWORDS';
export const UPDATE_FILTERS = 'UPDATE_FILTERS';
//ui
export const SHOW_ADVANCED_FILTERS = 'SHOW_ADVANCED_FILTERS';

//coordinates
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES';
export const UPDATE_COORDINATES_SUCCESS = 'UPDATE_COORDINATES_SUCCESS';
export const UPDATE_COORDINATES_ERROR = 'UPDATE_COORDINATES_ERROR';

//menus
export const RETRIEVE_MENUS = 'RETRIEVE_MENUS';
export const RETRIEVE_MENUS_SUCCESS = 'RETRIEVE_MENUS_SUCCESS';
export const RETRIEVE_MENUS_ERROR = 'RETRIEVE_MENUS_ERROR';
