//criteria
export const SET_DISTANCE = 'SET_DISTANCE';
export const SET_PRICE = 'SET_PRICE';
export const SET_SORT = 'SET_SORT';
export const SET_KEYWORDS = 'SET_KEYWORDS';
export const SET_ADDRESS = 'SET_ADDRESS';
export const SET_FOOD_CATEGORY = 'SET_FOOD_CATEGORY';

//ui
export const SHOW_ADVANCED_FILTERS = 'SHOW_ADVANCED_FILTERS';

//coordinates
export const UPDATE_COORDINATES = 'UPDATE_COORDINATES';
export const UPDATE_COORDINATES_SUCCESS = 'UPDATE_COORDINATES_SUCCESS';
export const UPDATE_COORDINATES_ERROR = 'UPDATE_COORDINATES_ERROR';

//menus
export const RETRIEVE_MENUS = 'RETRIEVE_MENUS';
export const RETRIEVE_MENUS_SUCCESS = 'RETRIEVE_MENUS_SUCCESS';
export const RETRIEVE_MENUS_ERROR = 'RETRIEVE_MENUS_ERROR';
