export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';
export const UPLOAD_AWS_ERROR = 'UPLOAD_AWS_ERROR';
export const UPDATE_USER_ERROR = 'UPLOAD_USER_ERROR';
export const RETRIEVE_USER_ERROR = 'RETRIEVE_USER_ERROR';
export const RETRIEVE_USER_SUCCESS = 'RETRIEVE_USER_SUCCESS';
